<div data-uk-observe="" id="wizard_advanced" role="application" class="wizard clearfix">
<div class="steps clearfix">
	<ul role="tablist">
		<li role="tab" class="" aria-disabled="false" aria-selected="true" style="background-color: #aaa;">
			<a href="#">
				<span class="number">1</span> <span class="title">Kata Sambutan</span></a></li>
		<li role="tab" class="" aria-disabled="false" aria-selected="true" style="background-color: #aaa;">
			<a href="#">
				<span class="number">2</span> <span class="title">Form Survey</span></a></li>
		<li role="tab" class="" aria-disabled="false" aria-selected="true" style="background-color: #aaa;">
			<a href="#">
				<span class="number">3</span> <span class="title">Pernyataan Persetujuan</span></a>
		</li>
		<li role="tab" class="first current"  aria-disabled="false" aria-selected="true">
			<a href="#">
				<span class="number">4</span> <span class="title">Finish</span></a>
		</li>
	</ul>
</div>
</div>
<div id="page_content">
		<div id="page_content_inner">
               <div class="md-card">
                  <div class="md-card-content">
                     <div>
                     Terima kasih atas partisipasi anda.
                     </div>
                  </div>
     	</div>               
	</div>
</div>
<script type="text/javascript">
	$(".loading-div-main").hide();
	$(".loading-div").hide();
</script>